import { Product } from '../types';

/**
 * Початковий каталог. Єдине джерело для сідування як локального JSON-сховку,
 * так і Vercel KV (через seedIfEmpty).
 */
export const seedProducts: Product[] = [
  {
    id: 'P-iph13-128',
    category: 'iphone',
    brand: 'Apple',
    model: 'iPhone 13',
    memory: '128 ГБ',
    condition: 'excellent',
    description: 'Акумулятор 92%. Без подряпин, ідеальний стан.',
    price: 21999,
    warranty: '30 днів',
    kit: 'Кабель, коробка',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/iph13/600/600',
    createdAt: '2026-07-20T10:00:00.000Z',
  },
  {
    id: 'P-iph12-64',
    category: 'iphone',
    brand: 'Apple',
    model: 'iPhone 12',
    memory: '64 ГБ',
    condition: 'good',
    description: 'Акумулятор 87%. Незначні потертості на рамці.',
    price: 15499,
    oldPrice: 17499,
    warranty: '14 днів',
    kit: 'Тільки пристрій',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/iph12/600/600',
    createdAt: '2026-07-22T10:00:00.000Z',
  },
  {
    id: 'P-iph11-128',
    category: 'iphone',
    brand: 'Apple',
    model: 'iPhone 11',
    memory: '128 ГБ',
    condition: 'used',
    description: 'Акумулятор 79%. Є сліди використання на екрані.',
    price: 11999,
    warranty: '14 днів',
    kit: 'Пристрій, кабель',
    status: 'reserved',
    photoUrl: 'https://picsum.photos/seed/iph11/600/600',
    createdAt: '2026-07-18T10:00:00.000Z',
  },
  {
    id: 'P-s23-256',
    category: 'samsung',
    brand: 'Samsung',
    model: 'Galaxy S23',
    memory: '256 ГБ',
    condition: 'excellent',
    description: 'Стан нового пристрою. Повний комплект.',
    price: 23999,
    warranty: '30 днів',
    kit: 'Кабель, коробка, документи',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/s23/600/600',
    createdAt: '2026-07-25T10:00:00.000Z',
  },
  {
    id: 'P-s21-128',
    category: 'samsung',
    brand: 'Samsung',
    model: 'Galaxy S21',
    memory: '128 ГБ',
    condition: 'good',
    description: 'Робочий стан відмінний, дрібні потертості корпусу.',
    price: 13499,
    oldPrice: 15999,
    warranty: '14 днів',
    kit: 'Тільки пристрій',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/s21/600/600',
    createdAt: '2026-07-15T10:00:00.000Z',
  },
  {
    id: 'P-mba-m1',
    category: 'laptop',
    brand: 'Apple',
    model: 'MacBook Air M1',
    memory: '8/256 ГБ',
    condition: 'excellent',
    description: "Цикли АКБ: 84. Ідеальний стан, без вм'ятин.",
    price: 28999,
    warranty: '30 днів',
    kit: 'Зарядка, коробка',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/mba/600/600',
    createdAt: '2026-07-26T10:00:00.000Z',
  },
  {
    id: 'P-tp-x1',
    category: 'laptop',
    brand: 'Lenovo',
    model: 'ThinkPad X1 Carbon',
    memory: '16/512 ГБ',
    condition: 'good',
    description: 'i7, потужний ультрабук. Незначні сліди на кришці.',
    price: 26499,
    warranty: '14 днів',
    kit: 'Зарядка',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/x1carbon/600/600',
    createdAt: '2026-07-19T10:00:00.000Z',
  },
  {
    id: 'P-ipad-air',
    category: 'tablet',
    brand: 'Apple',
    model: 'iPad Air 5',
    memory: '64 ГБ',
    condition: 'excellent',
    description: 'Wi-Fi, колір Starlight. Стан ідеальний.',
    price: 19999,
    warranty: '30 днів',
    kit: 'Зарядка, коробка',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/ipadair/600/600',
    createdAt: '2026-07-24T10:00:00.000Z',
  },
  {
    id: 'P-aw8-45',
    category: 'watch',
    brand: 'Apple',
    model: 'Apple Watch Series 8',
    memory: '45 мм',
    condition: 'good',
    description: 'GPS, АКБ 94%. Легкі потертості корпусу.',
    price: 9999,
    warranty: '14 днів',
    kit: 'Ремінець, зарядка',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/aw8/600/600',
    createdAt: '2026-07-21T10:00:00.000Z',
  },
  {
    id: 'P-airpods-pro2',
    category: 'airpods',
    brand: 'Apple',
    model: 'AirPods Pro 2',
    condition: 'excellent',
    description: 'Оригінал. Ємність кейса відмінна, шумозаглушення працює.',
    price: 6499,
    warranty: '14 днів',
    kit: 'Кейс, кабель, амбушури',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/airpodspro2/600/600',
    createdAt: '2026-07-27T10:00:00.000Z',
  },
  {
    id: 'P-magsafe',
    category: 'accessory',
    brand: 'Apple',
    model: 'MagSafe Charger',
    condition: 'good',
    description: 'Оригінальний бездротовий зарядний. Робочий.',
    price: 899,
    warranty: '7 днів',
    kit: 'Тільки зарядний',
    status: 'available',
    photoUrl: 'https://picsum.photos/seed/magsafe/600/600',
    createdAt: '2026-07-17T10:00:00.000Z',
  },
  {
    id: 'P-iph-se-sold',
    category: 'iphone',
    brand: 'Apple',
    model: 'iPhone SE 2020',
    memory: '64 ГБ',
    condition: 'good',
    description: 'Компактний, надійний. Продано.',
    price: 7999,
    warranty: '14 днів',
    kit: 'Пристрій, кабель',
    status: 'sold',
    photoUrl: 'https://picsum.photos/seed/iphse/600/600',
    createdAt: '2026-07-10T10:00:00.000Z',
  },
];
